# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e5be9c04c28ed572cfbeb1cd5e0effaf24852bde368e8985e934e1cba48c91f03aa9a7226c7ee56f2accf2d3ba318990f568932171015fa5c816aa68713d4c44

test:
  secret_key_base: a86bc31fd740688d27bfe4a03fab0edf2c738d506a75372252449dd261269293ece71dfd096b98f2a8fe5884438493d364217d55e0f09210ef80f4fbb003b349

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
